version: '3.8'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"

  aws-cli: &aws-cli
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    restart: on-failure
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    command: |
      dynamodb list-tables
      --endpoint-url http://dynamodb:8000
      --region eu-west-1

  to-do-table:
    <<: *aws-cli
    command:
      dynamodb create-table
      --table-name to-do-table
      --attribute-definitions AttributeName=listId,AttributeType=S
      --key-schema AttributeName=listId,KeyType=HASH
      --billing-mode PAY_PER_REQUEST
      --endpoint-url http://dynamodb:8000
      --region eu-west-1
