name: Run Unit Tests

on:
  push:
    branches: "**"

jobs:
  test-unit-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies (root)
        run: sudo npm i

      - name: Install dependencies (client)
        run: |
          cd client
          sudo npm i
          cd ..

      - name: Set up DynamoDB Local
        run: |
          docker-compose up -d
          sleep 10

      - name: Run unit tests
        run: npm run unit-test
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000
          AWS_ACCESS_KEY: dummy
          AWS_ACCESS_KEY_SECRET: dummy
          AWS_ACCESS_SESSION_TOKEN: dummy

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Stop DynamoDB Local
        if: always()
        run: docker-compose down